version: "4.0"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: baikal
      POSTGRES_PASSWORD: 12345678
    ports: ["5434"]
    command: -p 5434

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    depends_on: ["postgres"]
    ports:
      ["5050:5050"]

  go-app:
    build: .
    ports:
      ["3000:3000"]
    depends_on: ["postgres"]
