version: '3.9'
services:
  app:
    container_name: golang_container
    tty: true
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - baikal

  postgresdb:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
      - DATABASE_HOST=172.19.0.2
    expose:
      - "5434"
    ports:
      - "5434:5435"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    command: -p 5434
    networks:
      - baikal
      

  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - postgresdb
    ports:
      - "5050:5050"
    networks:
      - baikal

volumes:
  pgdata:

# Networks to be created to facilitate communication between containers
networks:
  baikal:
    driver: bridge