FROM golang:latest

ENV GO111MODULE=on

RUN mkdir /build

WORKDIR /build

RUN cd /build && git clone https://github.com/cmbaykal/go-postgre-task

RUN cd /build/go-postgre-task/ && go build -o main .

EXPOSE 3000 
EXPOSE 5432

ENTRYPOINT "/build/go-postgre-task/main"